# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z2_site', '0010_auto_20160826_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['detail']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='articles',
            field=models.ManyToManyField(blank=True, default=None, to='z2_site.Article'),
        ),
        migrations.AlterField(
            model_name='file',
            name='company',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='details',
            field=models.ManyToManyField(blank=True, default=None, to='z2_site.Detail'),
        ),
        migrations.AlterField(
            model_name='file',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
