# Generated by Django 4.2.1 on 2023-06-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museum_site', '0018_alter_article_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(help_text='Title used instead of ZFile title', max_length=120)),
                ('author_override', models.CharField(help_text='Author used instead of ZFile author', max_length=120)),
                ('company_override', models.CharField(help_text='Company used instead of ZFile company', max_length=120)),
                ('release_date_override', models.CharField(help_text='Release Date used instead of ZFile release date', max_length=20)),
                ('preview_image_override', models.CharField(help_text='Preview Image used instead of ZFile preview image', max_length=120)),
                ('zfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('when', models.DateTimeField()),
                ('preview_image', models.CharField(help_text='Preview Image used instead of ZFile preview image', max_length=120)),
                ('vod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
