# Generated by Django 4.2.1 on 2023-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream_entry',
            name='author_override',
            field=models.CharField(blank=True, help_text='Author used instead of ZFile author', max_length=120),
        ),
        migrations.AlterField(
            model_name='stream_entry',
            name='company_override',
            field=models.CharField(blank=True, help_text='Company used instead of ZFile company', max_length=120),
        ),
        migrations.AlterField(
            model_name='stream_entry',
            name='preview_image_override',
            field=models.CharField(blank=True, help_text='Preview Image used instead of ZFile preview image', max_length=120),
        ),
        migrations.AlterField(
            model_name='stream_entry',
            name='release_date_override',
            field=models.CharField(blank=True, help_text='Release Date used instead of ZFile release date', max_length=20),
        ),
        migrations.AlterField(
            model_name='stream_entry',
            name='title_override',
            field=models.CharField(blank=True, help_text='Title used instead of ZFile title', max_length=120),
        ),
    ]
