# Generated by Django 4.2.1 on 2023-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_alter_stream_entry_author_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='entries',
            field=models.ManyToManyField(blank=True, default=None, to='stream.stream_entry'),
        ),
    ]
