# Generated by Django 4.2.1 on 2023-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_stream_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='entries',
            field=models.ManyToManyField(blank=True, default=None, help_text='Stream Entries to be played during this stream', to='stream.stream_entry'),
        ),
    ]
