# Generated by Django 4.2.7 on 2023-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_stream_visible_alter_stream_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='vod',
        ),
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.CharField(choices=[('none', ''), ('wildcard', 'Unpreserved Worlds'), ('theme', 'Theme Stream'), ('bonus', 'Bonus Stream'), ('new', 'New Release Showcase'), ('guest', 'Special Guest Stream'), ('community', 'Community Event'), ('beyond', 'Beyond Worlds of ZZT'), ('dev', 'Game Dev Stream')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='stream',
            name='guests',
            field=models.CharField(blank=True, default=None, help_text='Guests on stream', max_length=300),
        ),
        migrations.AddField(
            model_name='stream',
            name='theme',
            field=models.CharField(blank=True, default=None, help_text='Theme for stream', max_length=120),
        ),
        migrations.AlterField(
            model_name='stream',
            name='preview_image',
            field=models.CharField(default='/static/screenshots/no_screenshot.png', help_text='Preview Image used on stream schedule', max_length=120),
        ),
    ]
