# Generated by Django 4.2.7 on 2024-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_remove_stream_vod_stream_category_stream_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='when',
            field=models.DateTimeField(help_text='6pm PST = 2:00 UTC next day. 12pm PST = 20:00 UTC'),
        ),
    ]
