# Generated by Django 4.2.11 on 2024-06-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_stream_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='key',
            field=models.CharField(blank=True, default='', help_text='Key to identify stream with', max_length=30),
        ),
    ]
