# Generated by Django 4.2.14 on 2024-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_stream_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='nonstandard_time',
            field=models.BooleanField(default=False, help_text='Add a disclaimer for streaming at an unusual date/time'),
        ),
    ]
