# Generated by Django 5.2.6 on 2025-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_stream_nonstandard_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='when',
            field=models.DateTimeField(help_text='Enter in Pacific time when creating. Value is converted and stored as UTC.'),
        ),
    ]
