# Generated by Django 5.2.6 on 2025-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_alter_stream_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(),
        ),
    ]
