# Generated by Django 3.2.15 on 2022-09-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('benco_image', models.CharField(max_length=25)),
                ('bencomic_image', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comic_id', models.IntegerField()),
                ('comic_account', models.CharField(choices=[('lemmy', 'Lemmy'), ('mr-shapiro', 'Mr. Shapiro'), ('nomad', "Nomad's ZZT Comics"), ('kaddar', 'Yellow Boarders'), ('frost', 'Frost'), ('revvy', 'The Prophesies of Revvy'), ('zamros', 'Zamros: The Comic'), ('ubgs', "Ol' Uncle Bo's Gamblin' Shack")], max_length=10)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('commentary', models.TextField(blank=True, default='', null=True)),
                ('transcript', models.TextField(blank=True, default=None, null=True)),
                ('characters', models.ManyToManyField(to='comic.Character')),
            ],
            options={
                'ordering': ['comic_account', 'comic_id'],
            },
        ),
    ]
