# Generated by Django 4.2.7 on 2025-01-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_character_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='characters',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
