# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20170127_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic_account',
            field=models.CharField(choices=[('benco', 'Benco'), ('bencomic', 'Bencomic'), ('lemmy', 'Lemmy'), ('mr-shapiro', 'Mr. Shapiro')], max_length=10),
        ),
    ]
