# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_comic_commentary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['comic_account', 'comic_id']},
        ),
    ]
