# Generated by Django 3.0.3 on 2020-05-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_auto_20170602_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic_account',
            field=models.CharField(choices=[('lemmy', 'Lemmy'), ('mr-shapiro', 'Mr. Shapiro'), ('nomad', "Nomad's ZZT Comics"), ('kaddar', 'Yellow Boarders'), ('frost', 'Frost'), ('revvy', 'The Prophesies of Revvy'), ('zamros', 'Zamros: The Comic'), ('ubgs', "Ol' Uncle Bo's Gamblin' Shack")], max_length=10),
        ),
    ]
