# Generated by Django 3.2.4 on 2021-06-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_auto_20200510_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
