# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField(default=b'')),
                ('css', models.TextField(blank=True, default=b'')),
                ('date', models.DateField(default=b'1970-01-01')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('filename', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('released', models.DateField(default=None, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('screenshot', models.CharField(max_length=80)),
                ('letter', models.CharField(db_index=True, max_length=1)),
                ('description', models.TextField(default=None, null=True)),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('rating', models.FloatField(default=5.0)),
                ('date', models.DateField()),
                ('ip', models.GenericIPAddressField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.File')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum_site.File'),
        ),
    ]
