# Generated by Django 3.2.7 on 2021-10-11 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('museum_site', '0001_initial'), ('museum_site', '0002_auto_20160131_2345'), ('museum_site', '0003_auto_20160131_2349'), ('museum_site', '0004_auto_20160204_1932'), ('museum_site', '0005_auto_20160207_1547'), ('museum_site', '0006_auto_20160211_2035'), ('museum_site', '0007_article_type'), ('museum_site', '0008_article_page'), ('museum_site', '0009_auto_20160816_2215'), ('museum_site', '0010_auto_20160826_2152'), ('museum_site', '0011_auto_20170112_0208'), ('museum_site', '0012_auto_20170112_0212'), ('museum_site', '0013_auto_20170201_0052'), ('museum_site', '0014_auto_20170307_2316'), ('museum_site', '0015_auto_20170321_0130'), ('museum_site', '0016_auto_20170414_2329'), ('museum_site', '0017_auto_20170415_0102'), ('museum_site', '0018_auto_20170816_0336'), ('museum_site', '0019_auto_20170816_0338'), ('museum_site', '0020_auto_20171008_0032'), ('museum_site', '0021_article_allow_comments'), ('museum_site', '0022_file_archive_name'), ('museum_site', '0023_auto_20181024_0251'), ('museum_site', '0024_auto_20181106_2138'), ('museum_site', '0025_auto_20181209_0608'), ('museum_site', '0026_auto_20190307_0205'), ('museum_site', '0027_auto_20190514_0458'), ('museum_site', '0028_auto_20191227_0408'), ('museum_site', '0029_zeta_config'), ('museum_site', '0030_file_zeta_config'), ('museum_site', '0031_auto_20200510_2313'), ('museum_site', '0032_auto_20200516_0248'), ('museum_site', '0033_zeta_config_category'), ('museum_site', '0034_auto_20200517_0317'), ('museum_site', '0035_auto_20200517_0318'), ('museum_site', '0036_wozzt_queue'), ('museum_site', '0037_auto_20200627_0339'), ('museum_site', '0038_auto_20200702_0402'), ('museum_site', '0039_wozzt_queue_category'), ('museum_site', '0040_auto_20200908_1830'), ('museum_site', '0041_upload'), ('museum_site', '0042_auto_20200930_1756'), ('museum_site', '0043_auto_20201022_0242'), ('museum_site', '0044_auto_20210118_1801'), ('museum_site', '0045_file_can_review'), ('museum_site', '0046_article_last_modified'), ('museum_site', '0047_auto_20210324_0243'), ('museum_site', '0048_auto_20210324_0344'), ('museum_site', '0049_auto_20210324_1957'), ('museum_site', '0050_remove_article_preview'), ('museum_site', '0051_article_last_revised'), ('museum_site', '0052_profile'), ('museum_site', '0053_auto_20210517_0046'), ('museum_site', '0054_auto_20210524_2216'), ('museum_site', '0055_auto_20210524_2234'), ('museum_site', '0056_auto_20210525_2235'), ('museum_site', '0057_profile_patron_visibility'), ('museum_site', '0058_review_user'), ('museum_site', '0059_remove_review_email'), ('museum_site', '0060_auto_20210611_0425'), ('museum_site', '0061_file_license'), ('museum_site', '0062_auto_20210620_2314'), ('museum_site', '0063_auto_20210703_2039'), ('museum_site', '0064_rename_visibile_detail_visible'), ('museum_site', '0065_auto_20210812_2116'), ('museum_site', '0066_rename_patron_level_profile_patronage'), ('museum_site', '0067_auto_20210812_2350'), ('museum_site', '0068_auto_20210817_2109'), ('museum_site', '0069_alter_profile_patron_email'), ('museum_site', '0070_upload_user'), ('museum_site', '0071_auto_20210823_2214'), ('museum_site', '0072_auto_20210825_2230'), ('museum_site', '0073_auto_20210826_0019'), ('museum_site', '0074_profile_accepted_tos'), ('museum_site', '0075_file_language'), ('museum_site', '0076_article_revision_details')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['detail'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField(default='')),
                ('css', models.TextField(blank=True, default='')),
                ('publish_date', models.DateField(default='1970-01-01')),
                ('published', models.IntegerField(choices=[(1, 'Published'), (2, 'Upcoming'), (3, 'Unpublished'), (0, 'Removed')], default=3)),
                ('schema', models.CharField(choices=[('text', 'Plaintext'), ('md', 'Markdown'), ('html', 'HTML'), ('django', 'Django'), ('80col', '80 Column Text')], default='django', max_length=6)),
                ('summary', models.CharField(blank=True, default='', max_length=150)),
                ('allow_comments', models.BooleanField(default=False)),
                ('spotlight', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date DB entry was last modified')),
                ('static_directory', models.CharField(blank=True, default='', help_text='Name of directory where static files for the article arestored.', max_length=120)),
                ('last_revised', models.DateTimeField(blank=True, default=None, help_text='Date article content was last revised', null=True)),
                ('revision_details', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Zeta_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('executable', models.CharField(blank=True, default='zzt.zip', max_length=128)),
                ('arguments', models.CharField(blank=True, default='', max_length=128)),
                ('commands', models.CharField(blank=True, default='', max_length=256)),
                ('blink_duration', models.DecimalField(decimal_places=3, default=0.466, max_digits=6)),
                ('charset', models.CharField(default='cp437', max_length=64)),
                ('audio_buffer', models.IntegerField(default=2048)),
                ('sample_rate', models.IntegerField(default=48000)),
                ('note_delay', models.IntegerField(default=1)),
                ('volume', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('category', models.IntegerField(choices=[(0, 'Recommended'), (1, 'Alternative'), (2, 'File Specific'), (3, 'Hidden')])),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('filename', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('screenshot', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('letter', models.CharField(db_index=True, max_length=1)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Set automatically. Do not adjust.')),
                ('company', models.CharField(blank=True, default='', max_length=80)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('details', models.ManyToManyField(blank=True, default=None, to='museum_site.Detail')),
                ('articles', models.ManyToManyField(blank=True, default=None, to='museum_site.Article')),
                ('release_source', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=80)),
                ('article_count', models.IntegerField(default=0, help_text='Set automatically. Do not adjust.')),
                ('checksum', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('superceded', models.ForeignKey(blank=True, db_column='superceded_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
                ('sort_title', models.CharField(blank=True, db_index=True, default='', help_text='Leave blank to set automatically', max_length=100)),
                ('playable_boards', models.IntegerField(blank=True, default=None, help_text='Set automatically. Do not adjust.', null=True)),
                ('total_boards', models.IntegerField(blank=True, default=None, help_text='Set automatically. Do not adjust.', null=True)),
                ('archive_name', models.CharField(blank=True, default='', help_text='ex: zzt_burgerj', max_length=80)),
                ('aliases', models.ManyToManyField(blank=True, default=None, to='museum_site.Alias')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date DB entry was last modified')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, default=None, help_text='Date File was published on the Museum', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date File was uploaded to the Museum', null=True)),
                ('uploader_ip', models.GenericIPAddressField(blank=True, default=None, editable=False, null=True)),
                ('zeta_config', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.zeta_config')),
                ('spotlight', models.BooleanField(default=True)),
                ('can_review', models.BooleanField(default=True)),
                ('license', models.CharField(default='Unknown', max_length=150)),
            ],
            options={
                'ordering': ['sort_title', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='WoZZT_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zzt_file', models.CharField(max_length=80)),
                ('board', models.IntegerField()),
                ('priority', models.IntegerField(default=10, help_text='Higher priority is used first')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
                ('board_name', models.CharField(default='', max_length=50)),
                ('dark', models.BooleanField(default=False)),
                ('shot_limit', models.IntegerField(default=255)),
                ('time_limit', models.IntegerField(default=0)),
                ('uuid', models.CharField(max_length=36)),
                ('zap', models.BooleanField(default=False)),
                ('category', models.CharField(default='wozzt', max_length=32)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('rating', models.FloatField(default=5.0)),
                ('date', models.DateField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date upload occurred')),
                ('edit_token', models.CharField(max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(choices=[(0, 'No contact'), (1, 'Contact if rejected'), (2, 'Contact if published/rejected')], default=0)),
                ('contacted', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=10, editable=False)),
                ('kind', models.CharField(choices=[('itch', 'Itch.io'), ('personal', 'Personal Webpage'), ('other', 'Other')], default='zgames', max_length=100)),
                ('hosted_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Download'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('patron', models.BooleanField(default=False)),
                ('patronage', models.IntegerField(default=0)),
                ('char', models.IntegerField(default=2)),
                ('fg', models.CharField(default='white', max_length=11)),
                ('bg', models.CharField(default='darkblue', max_length=11)),
                ('site_credits_name', models.CharField(blank=True, default='', max_length=100)),
                ('stream_credits_name', models.CharField(blank=True, default='', max_length=100)),
                ('max_upload_size', models.IntegerField(default=1048576)),
                ('files_published', models.IntegerField(default=0)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('reset_time', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=64)),
                ('activation_token', models.CharField(blank=True, max_length=64)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('patron_visibility', models.BooleanField(default=True)),
                ('bkzzt_topics', models.TextField(blank=True, max_length=2000)),
                ('closer_look_nominations', models.TextField(blank=True, max_length=2000)),
                ('closer_look_selections', models.TextField(blank=True, max_length=2000)),
                ('guest_stream_selections', models.TextField(blank=True, max_length=2000)),
                ('patron_tier', models.CharField(default=0, max_length=10)),
                ('stream_poll_nominations', models.TextField(blank=True, max_length=2000)),
                ('stream_selections', models.TextField(blank=True, max_length=2000)),
                ('patron_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('accepted_tos', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
