# Generated by Django 3.2.7 on 2021-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0001_squashed_0076_article_revision_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
