# Generated by Django 3.2.15 on 2022-09-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='test_field',
            field=models.CharField(default='Testing', max_length=10),
        ),
    ]
