# Generated by Django 3.2.7 on 2021-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0002_upload_announced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
