# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z2_site', '0002_auto_20160131_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='genre',
        ),
        migrations.AddField(
            model_name='file',
            name='genres',
            field=models.ManyToManyField(to='z2_site.Genre'),
        ),
    ]
