# Generated by Django 3.2.15 on 2022-09-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0003_review_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='test_field',
        ),
    ]
