# Generated by Django 3.2.7 on 2021-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0003_auto_20211028_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
