# Generated by Django 3.2.15 on 2022-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0004_remove_review_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='genre',
        ),
        migrations.AlterField(
            model_name='file',
            name='article_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached number of articles associated with this zip file.'),
        ),
    ]
