# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z2_site', '0004_auto_20160204_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='genres',
        ),
        migrations.AddField(
            model_name='file',
            name='genre',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
    ]
