# Generated by Django 3.2.7 on 2021-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0004_alter_file_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='license_source',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
