# Generated by Django 3.2.7 on 2021-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0005_file_license_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(default='temp', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
