# Generated by Django 3.2.15 on 2022-09-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0005_auto_20220925_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ssv_company',
        ),
    ]
