# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z2_site', '0006_auto_20160211_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='html', max_length=4),
            preserve_default=False,
        ),
    ]
