# Generated by Django 3.2.7 on 2021-11-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0006_detail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
    ]
