# Generated by Django 3.2.7 on 2021-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0007_file_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='genre',
            field=models.CharField(max_length=255),
        ),
    ]
