# Generated by Django 3.2.7 on 2021-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0008_alter_file_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(editable=False, max_length=80)),
                ('description', models.TextField(default='')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='article_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='articles',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='museum_site.Article'),
        ),
        migrations.AlterField(
            model_name='file',
            name='letter',
            field=models.CharField(db_index=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Series'),
        ),
    ]
