# Generated by Django 3.2.15 on 2022-10-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0008_file_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
