# Generated by Django 3.2.15 on 2022-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0009_auto_20221014_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
