# Generated by Django 3.2.15 on 2022-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0010_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plug_patreon',
            field=models.BooleanField(default=True, help_text='Add a plug for the Patreon at the end of the article'),
        ),
    ]
