# Generated by Django 3.2.7 on 2021-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0010_series_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='first_entry_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='last_entry_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
