# Generated by Django 3.2.15 on 2023-02-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0011_article_plug_patreon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.upload'),
        ),
        migrations.AlterField(
            model_name='download',
            name='kind',
            field=models.CharField(choices=[('zgames', 'Museum of ZZT Hosted'), ('itch', 'Itch.io'), ('personal', 'Personal Webpage'), ('other', 'Other')], default='zgames', max_length=100),
        ),
        migrations.CreateModel(
            name='Article_Category_Block',
            fields=[
                ('custom_block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_site.custom_block')),
            ],
            options={
                'abstract': False,
            },
            bases=('museum_site.custom_block',),
        ),
        migrations.CreateModel(
            name='Faux_Detailed_Block',
            fields=[
                ('custom_block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_site.custom_block')),
            ],
            options={
                'abstract': False,
            },
            bases=('museum_site.custom_block',),
        ),
    ]
