# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0011_auto_20170112_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum_site.Article'),
        ),
    ]
