# Generated by Django 3.2.7 on 2021-12-11 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0011_auto_20211202_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploader_ip',
        ),
        migrations.AlterField(
            model_name='file',
            name='articles',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Article'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date upload occurred'),
        ),
    ]
