# Generated by Django 3.2.17 on 2023-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0012_auto_20230201_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, default=None, help_text='Date the article was made public on the Museum', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema',
            field=models.CharField(choices=[('text', 'Plaintext'), ('html', 'HTML'), ('django', 'Django'), ('80col', '80 Column Text')], default='django', help_text='Schema for the article. Used to determine parsing method.', max_length=6),
        ),
    ]
