# Generated by Django 3.2.7 on 2022-01-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0013_article_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='superceded',
        ),
    ]
