# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0013_auto_20170201_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sort_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='superceded',
            field=models.ForeignKey(blank=True, db_column='superceded_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum_site.File'),
        ),
    ]
