# Generated by Django 3.2.17 on 2023-02-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0013_auto_20230215_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='first_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='last_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
