# Generated by Django 3.2.7 on 2022-01-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0014_remove_file_superceded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='email',
        ),
    ]
