# Generated by Django 3.2.17 on 2023-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0014_auto_20230215_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='footnotes',
            field=models.TextField(default='', help_text='Footnotes for article.'),
        ),
    ]
