# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0015_auto_20170321_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_warning',
        ),
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
