# Generated by Django 3.2.17 on 2023-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0015_article_footnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Dr. Dos', help_text='Author(s) of the article. Slash separated.', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='footnotes',
            field=models.TextField(blank=True, default='', help_text='Footnotes for article.'),
        ),
    ]
