# Generated by Django 3.2.7 on 2022-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0015_auto_20220107_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('source', models.CharField(max_length=160)),
                ('published', models.BooleanField(default=False)),
                ('suggestion', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date', '-id']},
        ),
    ]
