# Generated by Django 3.2.7 on 2022-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0016_auto_20220114_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
