# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z2_site', '0016_auto_20170414_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('text', 'Plaintext'), ('md', 'Markdown'), ('html', 'HTML'), ('django', 'Django')], max_length=6),
        ),
    ]
