# Generated by Django 3.2.7 on 2022-01-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0017_scroll_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='file',
            new_name='zfile',
        ),
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=False, help_text='Add a section for Disqus comments.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(help_text='Author(s) of the article. Slash separated.', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(help_text='Categorization of the article.', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', help_text='Body of the article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS. Must include <style></style> if set.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default='1970-01-01', help_text='Date the article was made public on the Museum'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Upcoming'), (3, 'Unpublished'), (0, 'Removed')], default=3, help_text='Publication Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='revision_details',
            field=models.TextField(blank=True, default='', help_text='Reference for revisions made to the article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema',
            field=models.CharField(choices=[('text', 'Plaintext'), ('md', 'Markdown'), ('html', 'HTML'), ('django', 'Django'), ('80col', '80 Column Text')], default='django', help_text='Schema for the article. Used to determine parsing method.', max_length=6),
        ),
        migrations.AlterField(
            model_name='article',
            name='secret',
            field=models.CharField(blank=True, default='', help_text='Per-article key to allow non-patrons to read unpublished articles', max_length=12),
        ),
        migrations.AlterField(
            model_name='article',
            name='spotlight',
            field=models.BooleanField(default=True, help_text='Allow this article to be visible on the front page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='static_directory',
            field=models.CharField(blank=True, default='', help_text='Name of directory where static files for the article are stored:<br>/museum_site/static/articles/[year|unk]/[static_directory]', max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='Blurb to summarize/pique interest in the article', max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Title of the the article.', max_length=100),
        ),
    ]
