# Generated by Django 4.2.1 on 2023-06-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0018_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Bugs And Glitches', 'Bugs And Glitches'), ('Closer Look', 'Closer Look'), ('Contest', 'Contest'), ('Featured World', 'Featured World'), ('Help', 'Help'), ('Historical', 'Historical'), ('Interview', 'Interview'), ("Let's Play", "Let's Play"), ('Livestream', 'Livestream'), ('Postmortem', 'Postmortem'), ('Publication Pack', 'Publication Pack'), ('Walkthrough', 'Walkthrough'), ('Misc', 'Misc.')], help_text='Categorization of the article.', max_length=50),
        ),
    ]
