# Generated by Django 3.2.12 on 2022-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0018_auto_20220120_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='Blurb to summarize/pique interest in the article', max_length=250),
        ),
        migrations.AlterField(
            model_name='scroll',
            name='content',
            field=models.TextField(default='', help_text='Lines starting with @ will be skipped. Initial whitespace is trimmed by DB, so an extra @ line is a fix.'),
        ),
    ]
