# Generated by Django 4.2.1 on 2023-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0019_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='explicit_warning',
            field=models.CharField(blank=True, default='', help_text="Specific warning for zfile's explicit content.", max_length=1024),
        ),
    ]
