# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0019_auto_20170816_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='playable_boards',
            field=models.IntegerField(blank=True, default=None, help_text='Set automatically. Do not adjust.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='total_boards',
            field=models.IntegerField(blank=True, default=None, help_text='Set automatically. Do not adjust.', null=True),
        ),
    ]
