# Generated by Django 3.2.12 on 2022-02-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0019_auto_20220222_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='description',
        ),
    ]
