# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0020_auto_20171008_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
    ]
