# Generated by Django 3.2.12 on 2022-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0020_rename_summary_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='can_review',
            field=models.IntegerField(choices=[(0, "Can't Review"), (1, 'Requires Approval'), (2, 'Can Review')], default=2),
        ),
    ]
