# Generated by Django 4.2.1 on 2023-06-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0020_file_explicit_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='scroll',
            name='title',
            field=models.CharField(default='Untitled', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scroll',
            name='zfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file'),
        ),
    ]
