# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-03 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0021_article_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='archive_name',
            field=models.CharField(blank=True, default='', help_text='ex: zzt_burgerj', max_length=80),
        ),
    ]
