# Generated by Django 4.2.3 on 2023-08-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0021_scroll_title_scroll_zfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='file',
            name='has_preview_image',
            field=models.BooleanField(default=False, help_text='Whether or not a preview image is available for this ZFile.'),
        ),
    ]
