# Generated by Django 3.2.12 on 2022-03-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0022_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
