# Generated by Django 4.2.3 on 2023-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0022_remove_file_screenshot_file_has_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scroll',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.CharField(db_index=True, default='', help_text='Unique identifier used for URLs and filtering. Filename w/out extension', max_length=50, unique=True),
        ),
    ]
