# Generated by Django 3.2.13 on 2022-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0023_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='category',
            field=models.CharField(choices=[('ZZT', 'ZZT'), ('SZZT', 'Super ZZT'), ('Media', 'Media'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
