# Generated by Django 3.2.13 on 2022-05-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0024_detail_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='detail',
            new_name='title',
        ),
    ]
