# Generated by Django 4.2.3 on 2023-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0024_feedback_tag_review_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_tag',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='file',
            name='feedback_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached count of all feedback associated with this zip file. Set automatically. Do not adjust.'),
        ),
        migrations.AlterField(
            model_name='feedback_tag',
            name='title',
            field=models.CharField(choices=[('Review', 'Review'), ('Content Warning', 'Content Warning'), ('Bug Report', 'Bug Report'), ('Hints', 'Hints and Solutions')], max_length=25),
        ),
        migrations.AlterField(
            model_name='file',
            name='review_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached count of review associated with this zip file. Set automatically. Do not adjust.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='Tag your feedback to identify what kind of information it provides. Any feedback with a rating will be automatically tagged as a review.', to='museum_site.feedback_tag'),
        ),
    ]
