# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0024_auto_20181106_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date File was uploaded to the Museum', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date DB entry was last modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='publish_date',
            field=models.DateTimeField(db_index=True, default=None, help_text='Date File was published on the Museum', null=True),
        ),
    ]
