# Generated by Django 4.2.3 on 2023-10-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0025_alter_feedback_tag_options_file_feedback_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spotlight',
            field=models.BooleanField(default=True, help_text='Boolean to mark feedback as suitable for display on the front page.'),
        ),
        migrations.AlterField(
            model_name='feedback_tag',
            name='title',
            field=models.CharField(choices=[('Review', 'Review'), ('Content Warning', 'Content Warning'), ('Bug Report', 'Bug Report'), ('Hints and Solutions', 'Hints and Solutions')], max_length=25),
        ),
    ]
