# Generated by Django 3.2.13 on 2022-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0025_auto_20220502_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(default='')),
                ('visible', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False, max_length=80)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
