# Generated by Django 2.1.7 on 2019-03-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0025_auto_20181209_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.AlterField(
            model_name='file',
            name='articles',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'page': 1}, to='museum_site.Article'),
        ),
        migrations.AlterField(
            model_name='file',
            name='superceded',
            field=models.ForeignKey(blank=True, db_column='superceded_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.File'),
        ),
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.File'),
        ),
    ]
