# Generated by Django 2.1.7 on 2019-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0026_auto_20190307_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='schema',
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Upcoming'), (3, 'Unpublished'), (0, 'Removed')], default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='articles',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Article'),
        ),
    ]
