# Generated by Django 3.2.13 on 2022-05-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0026_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='genres',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Genre'),
        ),
    ]
