# Generated by Django 4.2.3 on 2023-10-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0026_review_spotlight_alter_feedback_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='MD5 checksum of download. ZGames only. Blank for all others.', max_length=32),
        ),
        migrations.AddField(
            model_name='download',
            name='size',
            field=models.IntegerField(default=0, editable=False, help_text='Size in bytes of download. ZGames only. Blank for all others.'),
        ),
    ]
