# Generated by Django 3.2.13 on 2022-05-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0027_file_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Bugs And Glitches', 'Bugs And Glitches'), ('Closer Look', 'Closer Look'), ('Contest', 'Contest'), ('Featured Game', 'Featured Game'), ('Help', 'Help'), ('Historical', 'Historical'), ('Interview', 'Interview'), ("Let's Play", "Let's Play"), ('Livestream', 'Livestream'), ('Misc', 'Misc'), ('Postmortem', 'Postmortem'), ('Publication Pack', 'Publication Pack'), ('Walkthrough', 'Walkthrough')], help_text='Categorization of the article.', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
