# Generated by Django 4.2.7 on 2023-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0027_download_checksum_download_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['sort_title']},
        ),
        migrations.AlterField(
            model_name='file',
            name='can_review',
            field=models.IntegerField(choices=[(0, "Can't Give Feedback"), (1, 'Requires Approval'), (2, 'Can Give Feedback')], default=2, help_text='Choice of whether the file can be reviewed freely, pending approval, or not at all.'),
        ),
    ]
