# Generated by Django 2.2.6 on 2019-12-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0027_auto_20190514_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploader_ip',
            field=models.GenericIPAddressField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Upcoming'), (3, 'Unpublished'), (0, 'Removed')], default=3),
        ),
    ]
