# Generated by Django 4.2.7 on 2023-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0028_alter_file_options_alter_file_can_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='default_sort',
            field=models.CharField(choices=[('manual', 'Manual Order'), ('title', 'Title'), ('author', 'Author'), ('company', 'Company'), ('rating', 'Rating'), ('-release', 'Release Date (Newest)'), ('release', 'Release Date (Oldest)')], default='manual', help_text='The default sorting method when viewing this collection\'s contents. Set to "Manual Order" to display contents in an arbitrary order of your choosing.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_upload_size',
            field=models.IntegerField(default=2097152),
        ),
    ]
