# Generated by Django 3.2.13 on 2022-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0028_auto_20220518_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='archive_name',
            field=models.CharField(blank=True, default='', help_text="Identifier used on archive.org mirrors. Typically the 'zzt_' + zip name w/out extension. (ex: zzt_burgerj)", max_length=80),
        ),
        migrations.AlterField(
            model_name='file',
            name='article_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached number of articles associated with this zip file. Set automatically. Do not adjust.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.CharField(help_text='Slash-separated list of (major) developers', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='can_review',
            field=models.IntegerField(choices=[(0, "Can't Review"), (1, 'Requires Approval'), (2, 'Can Review')], default=2, help_text='Choice of whether the file can be reviewed freely, pending approval, or not at all.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='md5 checksum of zip file', max_length=32),
        ),
        migrations.AlterField(
            model_name='file',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Slash-separated list of companies the zfile is published under', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of contents. Wrap in quotes if written by author, leave unquoted for unofficial descriptions.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='explicit',
            field=models.BooleanField(default=False, help_text='Boolean to mark zfile as containing explicit content.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(help_text="Filename of the zip file containing this zfile's contents", max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.CharField(db_index=True, default='', help_text='Unique identifier used for URLs and filtering. Filename w/out extension', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(default='en', help_text="Slash-separated list of languages required to comprehend the zip file's contents. ISO 639-1 code. List defined in constants.py", max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='letter',
            field=models.CharField(db_index=True, editable=False, help_text='Letter used for filtering browse pages', max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='license',
            field=models.CharField(default='Unknown', help_text='License the file is released under.', max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='license_source',
            field=models.CharField(blank=True, default='', help_text='Source of licensing information.', max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='playable_boards',
            field=models.IntegerField(blank=True, default=None, help_text='(Estimated) count of boards visitable during gameplay. Set automatically. Do not adjust.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='rating',
            field=models.FloatField(blank=True, default=None, help_text='Mean score based on all reviews with scores attached.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='release_date',
            field=models.DateField(blank=True, default=None, help_text="Release date of zip file's contents.", null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='release_source',
            field=models.CharField(blank=True, default='', help_text='Source of release date when applicable.', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='review_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached number of review associated with this zip file. Set automatically. Do not adjust.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='screenshot',
            field=models.CharField(blank=True, default='', help_text='Filename for preview image. /static/images/screenshots/&lt;letter&gt;/&lt;screenshot&gt;', max_length=80),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, editable=False, help_text='Size in bytes of the zip file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sort_title',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Autogenerated value for actual title sorting. Strips articles and pads numbers to use leading digits.', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='spotlight',
            field=models.BooleanField(default=True, help_text='Boolean to mark zfile as being suitable for display on the front page.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(help_text='Canonical name of the release', max_length=80),
        ),
        migrations.AlterField(
            model_name='file',
            name='total_boards',
            field=models.IntegerField(blank=True, default=None, help_text='Total number of boards contained in zip file. Set automatically. Do not adjust.', null=True),
        ),
    ]
