# Generated by Django 3.0.3 on 2020-05-10 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0029_zeta_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='zeta_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.Zeta_Config'),
        ),
    ]
