# Generated by Django 3.2.13 on 2022-05-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0029_auto_20220526_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='license',
            new_name='file_license',
        ),
    ]
