# Generated by Django 4.2.7 on 2024-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0029_alter_collection_default_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_tag',
            name='key',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback_tag',
            name='title',
            field=models.CharField(choices=[('Review', 'Review'), ('Content Warning', 'Content Warning'), ('Bug Report', 'Bug Report'), ('Hints and Solutions', 'Hints and Solutions'), ('Table of Contents', 'Table of Contents')], max_length=25),
        ),
    ]
