# Generated by Django 3.0.3 on 2020-05-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0030_file_zeta_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zeta_config',
            old_name='comamnds',
            new_name='commands',
        ),
    ]
