# Generated by Django 3.2.13 on 2022-06-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0030_rename_license_file_file_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, editable=False, help_text='Filename', max_length=120)),
                ('path', models.CharField(db_index=True, editable=False, help_text='File Path', max_length=120)),
                ('ext', models.CharField(db_index=True, editable=False, help_text='File Extension', max_length=120)),
                ('mod_date', models.DateTimeField(default=None, help_text='File modification datetime')),
                ('directory', models.BooleanField(default=False)),
                ('crc32', models.CharField(editable=False, help_text="File's CRC32", max_length=12)),
                ('size', models.IntegerField(editable=False, help_text='File size in bytes')),
                ('zfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
            ],
        ),
    ]
