# Generated by Django 4.2.14 on 2024-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0030_feedback_tag_key_alter_feedback_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scroll',
            name='published',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='suggestion',
        ),
        migrations.AlterField(
            model_name='scroll',
            name='source',
            field=models.CharField(help_text='Will truncate leading https://museumofzzt.com on save', max_length=160),
        ),
    ]
