# Generated by Django 4.2.14 on 2024-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0031_remove_scroll_published_remove_scroll_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='complete',
            field=models.BooleanField(default=False, help_text='Series is expected to have no new articles added.'),
        ),
    ]
