# Generated by Django 3.0.3 on 2020-05-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0031_auto_20200510_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Date File was published on the Museum', null=True),
        ),
        migrations.AlterField(
            model_name='zeta_config',
            name='executable',
            field=models.CharField(blank=True, default='zzt.zip', max_length=128),
        ),
    ]
