# Generated by Django 3.2.13 on 2022-06-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0031_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
    ]
