# Generated by Django 3.0.3 on 2020-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0032_auto_20200516_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeta_config',
            name='category',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Alternative', 'Alternative'), ('File Specific', 'File Specific')], default='Recommended', max_length=64),
            preserve_default=False,
        ),
    ]
