# Generated by Django 3.2.13 on 2022-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0032_rename_contents_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='zfile',
        ),
        migrations.AlterField(
            model_name='content',
            name='ext',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='File Extension', max_length=120),
        ),
    ]
