# Generated by Django 3.2.13 on 2022-06-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0033_auto_20220606_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Content'),
        ),
    ]
