# Generated by Django 3.0.3 on 2020-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0034_auto_20200517_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeta_config',
            name='category',
            field=models.IntegerField(choices=[(0, 'Recommended'), (1, 'Alternative'), (2, 'File Specific')]),
        ),
    ]
