# Generated by Django 4.2.20 on 2025-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0034_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scroll',
            name='supports_twitch_redeem',
            field=models.BooleanField(default=True, help_text='If the scroll can be read via Twitch redeem'),
        ),
    ]
