# Generated by Django 3.2.13 on 2022-06-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum_site', '0035_auto_20220614_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, editable=False, help_text='Name of collection', max_length=120)),
                ('key', models.SlugField(help_text='Unique idenifier for collection', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of collection. Markdown supported.')),
                ('visibility', models.IntegerField(choices=[(0, 'Removed'), (1, 'Private'), (2, 'Unlisted'), (3, 'Public')], default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_count', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Description of file in collection. Markdown supported.')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum_site.collection')),
                ('zfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(through='museum_site.Collection_Entry', to='museum_site.File'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
