# Generated by Django 3.0.7 on 2020-06-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0035_auto_20200517_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoZZT_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zzt_file', models.CharField(max_length=80)),
                ('board', models.IntegerField()),
                ('priority', models.IntegerField(default=1, help_text='Higher priority is used first')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.File')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
