# Generated by Django 5.2.1 on 2025-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0035_article_slug_scroll_supports_twitch_redeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.DateField(default=None, help_text='Year of release when applicable. 01-01 used for sorting purposes.', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='release_source',
            field=models.CharField(blank=True, default='', help_text='Source of release date when applicable.', max_length=255),
        ),
    ]
