# Generated by Django 3.2.13 on 2022-06-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0036_auto_20220615_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='A short description of the collection. Plain text only.', max_length=250),
        ),
        migrations.AlterField(
            model_name='collection',
            name='key',
            field=models.SlugField(editable=False, help_text='Unique idenifier for collection', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(db_index=True, help_text='Name of collection', max_length=120),
        ),
    ]
