# Generated by Django 3.0.7 on 2020-07-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0037_auto_20200627_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wozzt_queue',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
