# Generated by Django 3.2.13 on 2022-06-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0037_auto_20220615_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='key',
            new_name='slug',
        ),
    ]
