# Generated by Django 5.2.1 on 2025-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0037_remove_download_checksum_remove_download_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.DateField(blank=True, default=None, help_text='Year of release when applicable. 01-01 used for sorting purposes.', null=True),
        ),
    ]
