# Generated by Django 5.2.1 on 2025-08-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0038_alter_file_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lock_slug',
            field=models.BooleanField(default=False, help_text='Check to disable recalculating slug on save.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(help_text='Automatically updated on save unless locked.', max_length=120),
        ),
    ]
