# Generated by Django 3.0.7 on 2020-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0038_auto_20200702_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='wozzt_queue',
            name='category',
            field=models.CharField(default='wozzt', max_length=32),
        ),
    ]
