# Generated by Django 3.2.13 on 2022-06-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0038_rename_key_collection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection_entry',
            old_name='description',
            new_name='collection_description',
        ),
    ]
