# Generated by Django 3.2.13 on 2022-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0039_rename_description_collection_entry_collection_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='collection_entry',
            options={'ordering': ['-order', 'id']},
        ),
        migrations.AddField(
            model_name='collection_entry',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='A short description of the collection displayed when browsing collections and not their contents. Plain text only.', max_length=250),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(db_index=True, help_text='The name of your collection. Used to generate URL for collection.', max_length=120),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Removed'), (1, 'Private'), (2, 'Unlisted'), (3, 'Public')], default=1, help_text='Permissions to access your collection. Collections with no items contained will not be displayed even if they are marked public.'),
        ),
        migrations.AlterField(
            model_name='collection_entry',
            name='collection_description',
            field=models.TextField(blank=True, default='', help_text='Optional description for the file as part of the collection. Markdown supported.'),
        ),
    ]
