# Generated by Django 5.2.6 on 2025-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0039_author_lock_slug_alter_author_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='author',
            name='lock_slug',
            field=models.BooleanField(default='-', help_text='Check to disable recalculating slug on save.'),
        ),
    ]
