# Generated by Django 3.2.13 on 2022-07-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0040_auto_20220702_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection_entry',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='collection',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='museum_site.file'),
        ),
    ]
