# Generated by Django 3.0.7 on 2020-09-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0040_auto_20200908_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date upload occurred')),
                ('edit_token', models.CharField(max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(choices=[(0, 'No contact'), (1, 'Contact if rejected'), (2, 'Contact if published/rejected')], default=0)),
                ('contacted', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.File')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
