# Generated by Django 5.2.6 on 2025-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0040_alter_company_options_alter_author_lock_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='otf_support',
            field=models.BooleanField(default=True, help_text='Show in On The Fly Collection tool.'),
        ),
        migrations.AddField(
            model_name='scroll',
            name='credit',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='lock_slug',
            field=models.BooleanField(default=False, help_text='Check to disable recalculating slug on save.'),
        ),
    ]
