# Generated by Django 3.2.13 on 2022-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0041_auto_20220706_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='default_sort',
            field=models.CharField(choices=[('manual', 'Manual Order'), ('title', 'Title'), ('author', 'Author'), ('company', 'Company'), ('rating', 'Rating'), ('release', 'Release Date (Newest)'), ('-release', 'Release Date (Oldest)')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='A short description of the collection displayed when browsing collections. Plain text only.', max_length=250),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Removed'), (1, 'Private'), (2, 'Unlisted'), (3, 'Public')], default=1, help_text='Permissions to access your collection. Collections with any associated files will not be displayed even if they are marked public.'),
        ),
    ]
