# Generated by Django 5.2.6 on 2025-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0041_collection_otf_support_scroll_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='otf_support',
            field=models.BooleanField(default=True, help_text='Show in On The Fly Collection tool. This can be disabled to avoid showing a completed collection in the OTF list.'),
        ),
    ]
