# Generated by Django 3.2.13 on 2022-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0042_auto_20220709_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='default_sort',
            field=models.CharField(choices=[('manual', 'Manual Order'), ('title', 'Title'), ('author', 'Author'), ('company', 'Company'), ('rating', 'Rating'), ('release', 'Release Date (Newest)'), ('-release', 'Release Date (Oldest)')], default='manual', help_text='The default sorting method when viewing this collection\'s contents. Set to "Manual Order" to display contents in an arbitrary order of your choosing.', max_length=20),
        ),
    ]
