# Generated by Django 3.0.7 on 2020-10-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0042_auto_20200930_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default='1970-01-01', null=True),
        ),
    ]
