# Generated by Django 3.2.15 on 2022-08-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0043_alter_collection_default_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='company',
            new_name='ssv_company',
        ),
    ]
