# Generated by Django 5.2.11 on 2026-05-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0043_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lock_slug',
            field=models.BooleanField(default=False, help_text='Check to disable recalculating slug on save.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='zfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file'),
        ),
    ]
