# Generated by Django 3.0.7 on 2021-01-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0043_auto_20201022_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='spotlight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='spotlight',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
