# Generated by Django 3.0.7 on 2021-01-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0044_auto_20210118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='can_review',
            field=models.BooleanField(default=True),
        ),
    ]
