# Generated by Django 3.2.15 on 2022-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0044_rename_company_file_ssv_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Company Name', max_length=120)),
                ('slug', models.SlugField(editable=False, max_length=120)),
            ],
        ),
    ]
