# Generated by Django 3.2.15 on 2022-08-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0045_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='companies',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Company'),
        ),
    ]
