# Generated by Django 3.0.7 on 2021-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0045_file_can_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date DB entry was last modified'),
        ),
    ]
