# Generated by Django 3.1.7 on 2021-03-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0046_article_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='static_directory',
            field=models.CharField(blank=True, default='', help_text='Name of directory where static files for the article are stored.', max_length=120),
        ),
        migrations.AlterField(
            model_name='wozzt_queue',
            name='priority',
            field=models.IntegerField(default=10, help_text='Higher priority is used first'),
        ),
    ]
