# Generated by Django 3.1.7 on 2021-03-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0047_auto_20210324_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='schema',
            field=models.CharField(choices=[('text', 'Plaintext'), ('md', 'Markdown'), ('html', 'HTML'), ('django', 'Django')], default='django', max_length=6),
        ),
    ]
