# Generated by Django 3.1.7 on 2021-03-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0048_auto_20210324_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='publish_date',
        ),
    ]
