# Generated by Django 3.1.7 on 2021-04-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0049_auto_20210324_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview',
        ),
    ]
