# Generated by Django 3.1.7 on 2021-05-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('museum_site', '0051_article_last_revised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('patron', models.BooleanField(default=False)),
                ('patron_level', models.IntegerField(default=0)),
                ('char', models.IntegerField(default=2)),
                ('fg', models.CharField(default='white', max_length=11)),
                ('bg', models.CharField(default='darkblue', max_length=11)),
                ('site_credits_name', models.CharField(blank=True, default='', max_length=100)),
                ('stream_credits_name', models.CharField(blank=True, default='', max_length=100)),
                ('max_upload_size', models.IntegerField(default=1048576)),
                ('files_uploaded', models.IntegerField(default=0)),
                ('pronouns', models.CharField(max_length=50)),
            ],
        ),
    ]
