# Generated by Django 3.1.7 on 2021-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0052_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
