# Generated by Django 3.1.7 on 2021-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0053_auto_20210517_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='static_directory',
            field=models.CharField(blank=True, default='', help_text='Name of directory where static files for the article arestored.', max_length=120),
        ),
    ]
