# Generated by Django 3.1.7 on 2021-05-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0054_auto_20210524_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activation',
            new_name='activation_token',
        ),
    ]
