# Generated by Django 3.1.7 on 2021-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0055_auto_20210524_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
