# Generated by Django 3.1.7 on 2021-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0056_auto_20210525_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patron_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
