# Generated by Django 3.1.7 on 2021-06-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0058_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
