# Generated by Django 3.2.4 on 2021-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0060_auto_20210611_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='license',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
