# Generated by Django 3.2.4 on 2021-07-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0062_auto_20210620_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='visibile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema',
            field=models.CharField(choices=[('text', 'Plaintext'), ('md', 'Markdown'), ('html', 'HTML'), ('django', 'Django'), ('80col', '80 Column Text')], default='django', max_length=6),
        ),
    ]
