# Generated by Django 3.2.4 on 2021-07-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0063_auto_20210703_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='visibile',
            new_name='visible',
        ),
    ]
