# Generated by Django 3.2.4 on 2021-08-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0065_auto_20210812_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='patron_level',
            new_name='patronage',
        ),
    ]
