# Generated by Django 3.2.4 on 2021-08-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0066_rename_patron_level_profile_patronage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bkzzt_topics',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='closer_look_nominations',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='closer_look_selections',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guest_stream_selections',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stream_poll_nominations',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stream_selections',
            field=models.TextField(blank=True, editable=False, max_length=2000),
        ),
    ]
