# Generated by Django 3.2.4 on 2021-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0067_auto_20210812_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patron_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bkzzt_topics',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='closer_look_nominations',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='closer_look_selections',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guest_stream_selections',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stream_selections',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
