# Generated by Django 3.2.4 on 2021-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0068_auto_20210817_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patron_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
