# Generated by Django 3.2.4 on 2021-08-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0070_upload_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='files_uploaded',
            new_name='files_published',
        ),
        migrations.AlterField(
            model_name='profile',
            name='patron_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
