# Generated by Django 3.2.4 on 2021-08-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0071_auto_20210823_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=10, editable=False)),
                ('kind', models.CharField(choices=[('zgames', 'Museum of ZZT'), ('itch', 'Itch.io'), ('personal', 'Personal Webpage'), ('other', 'Other')], default='zgames', max_length=100)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.ManyToManyField(blank=True, default=None, to='museum_site.Download'),
        ),
    ]
