# Generated by Django 3.2.4 on 2021-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0072_auto_20210825_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='hosted_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='download',
            name='kind',
            field=models.CharField(choices=[('itch', 'Itch.io'), ('personal', 'Personal Webpage'), ('other', 'Other')], default='zgames', max_length=100),
        ),
    ]
