# Generated by Django 3.2.4 on 2021-09-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0073_auto_20210826_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_tos',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
