# Generated by Django 3.2.4 on 2021-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0074_profile_accepted_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
