ZETA_ZZT32R = 1
ZETA_ZFILE_VARIETY = 2
ZETA_ZZT_NOBLINK = 3
ZETA_SZZT20 = 4
ZETA_ZFILE_ALGORITHM = 5
# UNUSED PK 6
ZETA_ZFILE_BANANA_QUEST = 7
ZETA_INCLUDED_EXE = 8
ZETA_ZFILE_DAEDALUS_OBELISK = 9
# UNUSED PK 10
ZETA_ZFILE_MOUSTACHE4 = 11
ZETA_ZFILE_MWZZT = 12
ZETA_CLEENZZT = 13
ZETA_GENERIC_FONT = 14
ZETA_ZFILE_KIYB = 15
ZETA_ZFILE_KITTEN_HALLWAY = 16
ZETA_ZFILE_BUBBAS_BUBBLES = 17
ZETA_GENERIC_FONT_SZZT = 18
ZETA_ZFILE_ZOO_OF_ZZT = 19
ZETA_RESTRICTED = 20
ZETA_ZFILE_BEAR_WITH_ME = 21
ZETA_CLASSICZOO = 22
