import os
import sys

import django

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "museum.settings")
django.setup()

from django.contrib.auth.models import User  # noqa: E402

from museum_site.models import *  # noqa: E402


def main():
    print(
        "This script will generate Upload objects for Files which did not \
        have one created at time of archival."
    )
    input("Press Enter to begin.")
    qs = File.objects.all().order_by("id")
    ids = []

    # Get all used IDs
    for f in qs:
        ids.append(f.id)

    # Get all upload object file_ids
    qs = Upload.objects.all().order_by("id")

    files_with_uploads = []

    for u in qs:
        files_with_uploads.append(u.file_id)

    files_without_uploads = []

    for i in ids:
        if i not in files_with_uploads and (f is not None):
            files_without_uploads.append(i)

    print("FILES WITH UPLOAD OBJECTS:", len(files_with_uploads))
    print("FILES WITHOUT UPLOAD OBJECTS:", len(files_without_uploads))

    for i in files_without_uploads:
        f = File.objects.get(pk=i)
        u = Upload()
        u.generate_edit_token()
        if f.uploader_ip:
            u.ip = f.uploader_ip
        if f.upload_date:
            u.date = f.upload_date
        else:
            u.date = "1970-01-01 00:00:00"
        u.notes = "Autogenerated Upload Object. Dec. 10, 2021"
        u.file_id = f.id
        u.save()
        print(u)

    return True


if __name__ == '__main__':
    main()
