# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('benco_image', models.CharField(max_length=25)),
                ('bencomic_image', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stripcreator_id', models.IntegerField()),
                ('stripcreator_account', models.CharField(choices=[('benco', 'Benco'), ('bencomic', 'Bencomic')], max_length=8)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('transcript', models.TextField()),
                ('characters', models.ManyToManyField(to='bencomic.Character')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
