import os

# Bluesky
BLUESKY_USER = os.environ.get("MOZ_BLUESKY_USER", "-UNDEFINED-")
BLUESKY_PASSWORD = os.environ.get("MOZ_BLUESKY_PASSWORD", "-UNDEFINED-")

# Internet Archive
IA_ACCESS = os.environ.get("MOZ_IA_ACCESS", "!c;LOCKED FILE")
IA_SECRET = os.environ.get("MOZ_IA_SECRET", "-UNDEFINED-")

# Patreon
BETA_USERNAME = os.environ.get("MOZ_BETA_USERNAME", "-UNDEFINED-")
BETA_PASSWORD = os.environ.get("MOZ_BETA_PASSWORD", "-UNDEFINED-")
PASSWORD2DOLLARS = os.environ.get("MOZ_PASSWORD2DOLLARS", "2DOLLARS")
PASSWORD5DOLLARS = os.environ.get("MOZ_PASSWORD5DOLLARS", "5DOLLARS")

# Mastodon (mastodon.social)
MASTODON_CLIENT_KEY = os.environ.get("MOZ_MASTODON_CLIENT_KEY", "-UNDEFINED-")
MASTODON_CLIENT_SECRET = os.environ.get("MOZ_MASTODON_CLIENT_SECRET", "-UNDEFINED-")
MASTODON_ACCESS_TOKEN = os.environ.get("MOZ_MASTODON_ACCESS_TOKEN", "-UNDEFINED-")
MASTODON_EMAIL = os.environ.get("MOZ_MASTODON_EMAIL", "-UNDEFINED-")
MASTODON_PASS = os.environ.get("MOZ_MASTODON_PASS", "-UNDEFINED-")
MASTODON_SECRETS_FILE = os.environ.get("MOZ_MASTODON_SECRETS_FILE", "-UNDEFINED-")

# Tumblr -- https://api.tumblr.com/console/calls/user/info
TUMBLR_OAUTH_CONSUMER = os.environ.get("MOZ_TUMBLR_OAUTH_CONSUMER", "-UNDEFINED-")
TUMBLR_OAUTH_CONSUMER_SECRET = os.environ.get("MOZ_TUMBLR_OAUTH_CONSUMER_SECRET", "-UNDEFINED-")
TUMBLR_OAUTH_TOKEN = os.environ.get("MOZ_TUMBLR_OAUTH_TOKEN", "-UNDEFINED-")
TUMBLR_OAUTH_SECRET = os.environ.get("MOZ_TUMBLR_OAUTH_SECRET", "-UNDEFINED-")

# Twitter
TWITTER_CONSUMER_KEY = os.environ.get("MOZ_TWITTER_CONSUMER_KEY", "-UNDEFINED-")
TWITTER_CONSUMER_SECRET = os.environ.get("MOZ_TWITTER_CONSUMER_SECRET", "-UNDEFINED-")
TWITTER_OAUTH_TOKEN = os.environ.get("MOZ_TWITTER_OAUTH_TOKEN", "-UNDEFINED-")
TWITTER_OAUTH_SECRET = os.environ.get("MOZ_TWITTER_OAUTH_SECRET", "-UNDEFINED-")
TWITTER_BEARER_TOKEN = os.environ.get("MOZ_TWITTER_BEARER_TOKEN", "-UNDEFINED-")

# Discord
DISCORD_INVITE_URL = os.environ.get("MOZ_DISCORD_INVITE_URL", "-UNDEFINED-")
WEBHOOK_URL = os.environ.get("MOZ_WEBHOOK_URL", "-UNDEFINED-")
NEW_UPLOAD_WEBHOOK_URL = os.environ.get("MOZ_NEW_UPLOAD_WEBHOOK_URL", "-UNDEFINED-")
NEW_REVIEW_WEBHOOK_URL = os.environ.get("MOZ_NEW_REVIEW_WEBHOOK_URL", "-UNDEFINED-")

DISCORD_WEBHOOK_ANNOUNCEMENTS_URL = os.environ.get("MOZ_DISCORD_WEBHOOK_ANNOUNCEMENTS_URL", "-UNDEFINED-")
DISCORD_WEBHOOK_FEED_URL = os.environ.get("MOZ_DISCORD_WEBHOOK_FEED_URL", "-UNDEFINED-")
DISCORD_WEBHOOK_TEST_URL = os.environ.get("MOZ_DISCORD_WEBHOOK_TEST_URL", "-UNDEFINED-")
DISCORD_WEBHOOK_PATRONS_URL = os.environ.get("MOZ_DISCORD_WEBHOOK_PATRONS_URL", "-UNDEFINED-")

# SMTP
SMTP_HOST = os.environ.get("MOZ_SMTP_HOST", "localhost")
SMTP_PORT = os.environ.get("MOZ_SMTP_PORT", 0)
SMTP_AUTH_USER = os.environ.get("MOZ_SMTP_AUTH_USER", "-UNDEFINED-")
SMTP_AUTH_PASS = os.environ.get("MOZ_SMTP_AUTH_PASS", "-UNDEFINED-")

# IP Address Related
REMOTE_ADDR_HEADER = os.environ.get("MOZ_REMOTE_ADDR_HEADER", "REMOTE_ADDR")

# TODO: This is janky and temporary
BANNED_IPS = [
    # "127.0.0.*",
]

# External Article Development
EXTERNAL_ARTICLE_PATH = os.environ.get("MOZ_EXTERNAL_ARTICLE_PATH", "-UNDEFINED-")
