CATEGORY_DESCRIPTIONS = {
"bugs-and-glitches": "<p>Articles which discuss bugs and glitches in ZZT and how others have exploited them to their benefit.</p>",
"closer-look": "<p>A core feature of the Museum. Closer Looks are articles that (typically) focus on a specific ZZT world and document a journey through it from start to finish, discussing gameplay, design, coding, and the legacy of the released world.</p>",
"contest": "<p>Articles which relate to ZZT contests such as award ceremonies and (un)official scores for events.</p>",
"featured-world": "<p>Articles which cover specific ZZT and Super ZZT worlds of some notability. These include historical reviews for community awards such as \"Game of the Month\" awards as well as more recent reviews to better showcase ZZT worlds that are well worth your time.</p>",
"help": "<p>Articles containing help on a variety of topics. This category contains articles that answer questions about ZZT, how to run it, how to create games for it, reference materials, game recommendations, and various other \"how-to\" guides.</p>",
"historical": "<p>Articles which contain documents and historical information including scans, newsletters, and message board logs.</p>",
"interview": "<p>Articles in which a subject is interviewed about topics including their past/present/future with ZZT as well as discussing non-ZZT games they created inspired by ZZT.</p>",
"lets-play": "<p>Articles which contain YouTube embeds of Worlds of ZZT playthroughs that were not streamed live. These playthroughs can also be watched directly on the <a href='https://museumofzzt.com/youtube' target='_blank'>Worlds of ZZT YouTube channel</a>.</p>",
"livestream": "<p>Articles which contain YouTube embeds of Worlds of ZZT livestreams, and in rare cases livestreams done by other individuals (published here with permission). Worlds of ZZT livestreams can also be watched directly on the <a href='https://museumofzzt.com/youtube' target='_blank'>Worlds of ZZT YouTube channel</a>.</p>",
"postmortem": "<p>Articles in which authors of ZZT worlds discuss the creation of their game, lessons learned, and provide useful information about the obstacles overcome in creating a finished release.</p>",
"publication-pack": "<p>Articles which provide brief overviews to newly published worlds on the Museum of ZZT. Information is purposefully brief and a few screenshots of each published item are included when possible.</p>",
"walkthrough": "<p>Articles which serve as guides for ZZT worlds. Generally in text format, but more recent entries include video demonstrations and author produced guidebooks.</p>",
"misc": "<p>If it doesn't fit in anywhere else. It fits in here.</p>",
}
