# Generated by Django 3.2.15 on 2022-09-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('poll', '0001_initial'), ('poll', '0002_auto_20180101_0315'), ('poll', '0003_auto_20190307_0205'), ('poll', '0004_poll_title'), ('poll', '0005_auto_20210611_0425'), ('poll', '0006_auto_20210830_2122'), ('poll', '0007_alter_option_options'), ('poll', '0008_option_requested_by'), ('poll', '0009_alter_vote_email')]

    initial = True

    dependencies = [
        ('museum_site', '0020_auto_20171008_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300)),
                ('backer', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
                ('played', models.BooleanField(default=False)),
                ('requested_by', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'ordering': ['played', 'file__title'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('secret', models.CharField(blank=True, default='', max_length=32)),
                ('option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option1', to='poll.option')),
                ('option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option2', to='poll.option')),
                ('option3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option3', to='poll.option')),
                ('option4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option4', to='poll.option')),
                ('option5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option5', to='poll.option')),
                ('title', models.CharField(default='Closer Look Poll', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.option')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.poll')),
            ],
        ),
    ]
