# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-01 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
