# Generated by Django 3.2.15 on 2022-09-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museum_site', '0002_initial'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300)),
                ('backer', models.BooleanField(default=False)),
                ('played', models.BooleanField(default=False)),
                ('requested_by', models.CharField(blank=True, default='', max_length=80)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.file')),
            ],
            options={
                'ordering': ['played', 'file__title'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('secret', models.CharField(blank=True, default='', max_length=32)),
                ('option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option1', to='poll.option')),
                ('option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option2', to='poll.option')),
                ('option3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option3', to='poll.option')),
                ('option4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option4', to='poll.option')),
                ('option5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option5', to='poll.option')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.option')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.poll')),
            ],
        ),
    ]
