# Generated by Django 2.1.7 on 2019-03-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180101_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_site.File'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option1', to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option2', to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option3', to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option4', to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option5', to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Option'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Poll'),
        ),
    ]
