# Generated by Django 4.2.17 on 2025-01-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_option_poll_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(blank=True, default=None, to='poll.option'),
        ),
    ]
