# Generated by Django 2.2.6 on 2019-12-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190307_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Closer Look Poll', max_length=80),
            preserve_default=False,
        ),
    ]
