# Generated by Django 4.2.17 on 2025-01-03 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='author_override',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='option',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='option',
            name='preview_image_override',
            field=models.CharField(blank=True, help_text='Preview Image used instead of ZFile preview image', max_length=120),
        ),
        migrations.AddField(
            model_name='option',
            name='title_override',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
