# Generated by Django 5.2.1 on 2025-07-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_option_author_override_option_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option5',
        ),
    ]
