# Generated by Django 3.2.4 on 2021-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210611_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-played', 'file__title']},
        ),
        migrations.AddField(
            model_name='option',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
