# Generated by Django 3.2.4 on 2021-09-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210830_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['played', 'file__title']},
        ),
    ]
