# Generated by Django 3.2.7 on 2021-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_option_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='requested_by',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
