# Generated by Django 3.2.7 on 2021-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_option_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
