# Generated by Django 3.2.17 on 2023-02-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='key',
            new_name='title',
        ),
    ]
