# Generated by Django 3.2.17 on 2023-03-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0002_rename_key_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_render',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='image_render_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
