# Generated by Django 3.2.17 on 2023-03-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0004_remove_event_image_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('media_1', models.CharField(blank=True, default='', max_length=255)),
                ('media_2', models.CharField(blank=True, default='', max_length=255)),
                ('media_3', models.CharField(blank=True, default='', max_length=255)),
                ('media_4', models.CharField(blank=True, default='', max_length=255)),
                ('tweet_id', models.IntegerField(default=0)),
                ('tumblr_id', models.IntegerField(default=0)),
                ('mastodon_id', models.IntegerField(default=0)),
                ('patreon_id', models.IntegerField(default=0)),
                ('cohost_id', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zap.event')),
            ],
        ),
    ]
