# Generated by Django 3.2.17 on 2023-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cohost_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='mastodon_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='patreon_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='tumblr_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweet_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
