# Generated by Django 3.2.17 on 2023-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0006_auto_20230324_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=80),
        ),
    ]
