# Generated by Django 4.2.14 on 2024-10-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0007_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cohost_id',
        ),
    ]
