# Generated by Django 4.2.14 on 2024-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0008_remove_post_cohost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bluesky_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
