# Generated by Django 4.2.17 on 2024-12-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0009_post_bluesky_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
